server:
  port: ${PORT}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

gateway:
  host:
    pdf-services: https://pdf-services.herokuapp.com
